version: '3.8'

services:
  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_DATABASE=product_service_db
      MYSQL_USER=devuser
      MYSQL_PASSWORD=Pasindu119
      MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3307:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product-db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      product-db:
        condition: service_healthy

volumes:
  product-db-data: