server:
  port: 8083

spring:
  application:
    name: product-service  # This is the name that will be used in Eureka
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    username: devuser
    password: Pasindu119
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/  # URL of Eureka Server
#  instance:
#    prefer-ip-address: true  # Optional: Uses IP instead of hostname
